# package sources should be placed in ${PWD}/root
# nfpm should run from the same directory with a config
name: "clickhouse-common-static"
description: |
  Common files for ClickHouse
    ClickHouse is a column-oriented database management system
    that allows generating analytical data reports in real time.
    This package provides common files for both clickhouse server and client

# Common packages config
arch: "${DEB_ARCH}" # amd64, arm64
platform: "linux"
version: "${VERSION_STRING}"
vendor: "ClickHouse Inc."
homepage: "https://clickhouse.com"
license: "Apache"
section: "database"
priority: "optional"
maintainer: "ClickHouse Dev Team <packages+linux@clickhouse.com>"
deb:
  fields:
    Source: clickhouse

# Package specific content
replaces:
- clickhouse-common
- clickhouse-server-base
provides:
- clickhouse-common
- clickhouse-server-base
suggests:
- clickhouse-common-static-dbg

contents:
- src: usr/bin/clickhouse
  dst: /usr/bin/clickhouse
- src: usr/bin/clickhouse-extract-from-config
  dst: /usr/bin/clickhouse-extract-from-config
- src: usr/share/bash-completion/completions
  dst: /usr/share/bash-completion/completions
- src: usr/share/clickhouse
  dst: /usr/share/clickhouse
# docs
- src: usr/share/doc/clickhouse/LICENSE
  dst: /usr/share/doc/clickhouse-common-static/LICENSE
- src: usr/share/doc/clickhouse/NOTICE.txt
  dst: /usr/share/doc/clickhouse-common-static/NOTICE.txt

