# package sources should be placed in ${PWD}/root
# nfpm should run from the same directory with a config
name: "clickhouse-keeper"
description: |
  Static clickhouse-keeper binary
    A stand-alone clickhouse-keeper package


#
# Common packages config
arch: "${DEB_ARCH}" # amd64, arm64
platform: "linux"
version: "${VERSION_STRING}"
vendor: "ClickHouse Inc."
homepage: "https://clickhouse.com"
license: "Apache"
section: "database"
priority: "optional"
maintainer: "ClickHouse Dev Team <packages+linux@clickhouse.com>"
deb:
  fields:
    Source: clickhouse

# Package specific content
conflicts:
- clickhouse-server
suggests:
- clickhouse-keeper-dbg

contents:
- src: etc/clickhouse-keeper/keeper_config.xml
  dst: /etc/clickhouse-keeper/keeper_config.xml
  type: config|noreplace
- src: clickhouse-keeper.service
  dst: /lib/systemd/system/clickhouse-keeper.service
- src: usr/bin/clickhouse-keeper
  dst: /usr/bin/clickhouse-keeper
- src: clickhouse-keeper
  dst: /usr/bin/clickhouse-keeper-client
  type: symlink
- src: clickhouse-keeper
  dst: /usr/bin/clickhouse-keeper-converter
  type: symlink
# docs
- src: usr/share/doc/clickhouse/LICENSE
  dst: /usr/share/doc/clickhouse-keeper/LICENSE
- src: usr/share/doc/clickhouse/NOTICE.txt
  dst: /usr/share/doc/clickhouse-keeper/NOTICE.txt

scripts:
  postinstall: ./clickhouse-keeper.postinstall
